window.SKIN_DEFINITIONS = {
  default: {
    name: "Default",
    copies: "N/A",
    color: "#335699",
    gameUnlock: true,
  },
  chairlord: {
    name: "Chairlord",
    copies: "1/1",
    color: "#d4d2c7",
    desc: "First Place",
    gold: true,
    artist: "Chairlord",
    firstPlace: true,
  },
  sunset: {
    name: "Sunset",
    copies: "1/2",
    color: "#eaee00",
    artist: "chairlord",
  },
  rainbowmonster: {
    name: "Rainbow Monster",
    copies: "1/10",
    color: "#f51600",
    artist: "chairlord",
  },
  burningheart: {
    name: "Burning Heart",
    copies: "1/3",
    color: "#130c10",
    artist: "Seppe",
  },
  tv: { name: "TV", copies: "1/2", color: "#f1eef4", artist: "Seppe" },
  cubemouth: {
    name: "Cube Mouth",
    copies: "1/6",
    color: "#1101d1",
    artist: "chairlord",
  },
  firstplacedaddy: {
    name: "First Place Daddy",
    copies: "1/1",
    color: "#eee6e6",
    desc: "First Place",
    gold: true,
    artist: "Ligmadaddy69 & Torgaar",
    firstPlace: true,
  },
  dino: {
    name: "Dino",
    copies: "1/20",
    color: "#aefe61",
    artist: "Mcdongos",
  },
  emo: {
    name: "Emotions",
    copies: "1/3",
    color: "#398dfa",
    artist: "ejohnson",
  },
  emo2: {
    name: "Emotions 2",
    copies: "1/5",
    color: "#476ffa",
    artist: "ejohnson",
  },
  emo3: {
    name: "Emotions 3",
    copies: "1/5",
    color: "#388bf6",
    artist: "ejohnson",
  },
  kingbanana: {
    name: "King Banana",
    copies: "1/13",
    color: "#f2c94c",
    artist: "Torgaar",
    unlockCode: true,
  },
  j_imbo: {
    name: "J_imbo",
    copies: "1/1",
    color: "#0a9cdd",
    desc: "First Place",
    gold: true,
    artist: "Torgaar",
    firstPlace: true,
  },
  bluecoin: {
    name: "Blue Gem",
    copies: "N/A",
    color: "#2976bd",
    artist: "Torgaar",
    gameUnlock: true,
  },
  coolguy: {
    name: "Cool Guy",
    copies: "1/5",
    color: "#009fe3",
    artist: "Torgaar",
    competitive: true,
  },
  goldcoolguy: {
    name: "Golden Cool Guy",
    copies: "1/1",
    color: "#dcb86f",
    artist: "Torgaar",
    competitive: true,
  },
  rainbownoir: {
    name: "Rainbow Monster (Noir)",
    copies: "1/3",
    color: "#7e8185",
    artist: "Chairlord & Torgaar",
  },
  rainbowretro: {
    name: "Rainbow Monster (Retro)",
    copies: "1/3",
    color: "#e9a13e",
    artist: "Chairlord & Torgaar",
  },
  vintageemo: {
    name: "Emotions (Vintage)",
    copies: "1/3",
    color: "#85bdd4",
    artist: "ejohnson & Torgaar",
  },
  coolguyglassesdown: {
    name: "Cool Guy (Glasses Down)",
    copies: "1/1",
    color: "#019adc",
    artist: "Torgaar",
    competitive: true,
  },
  coolguyreflection: {
    name: "Cool Guy (Reflection)",
    copies: "1/3",
    color: "#009fe3",
    artist: "Torgaar",
  },
  dasher: {
    name: "Dasher",
    copies: "1/1",
    color: "#e8e800",
    desc: "Honorary",
    gold: true,
    artist: "Chairlord",
    honorary: true,
  },
  dasher2: {
    name: "Dasher 2",
    copies: "1/1",
    color: "#00e813",
    desc: "Honorary",
    gold: true,
    artist: "Chairlord",
    honorary: true,
  },
  metallic: {
    name: "Metallic Anger",
    copies: "N/A",
    color: "#df433d",
    artist: "Torgaar",
    gameUnlock: true,
    versions: [
      { name: "Original", img: "metallic_old.png" },
      { name: "Current", img: "metallic.png" },
    ],
  },
  legendsgalaxy: {
    name: "Galaxy (Legends Edition)",
    copies: "1/3",
    color: "#71b5d5",
    artist: "Torgaar",
    competitive: true,
  },
  galaxy: {
    name: "Galaxy",
    copies: "N/A",
    color: "#243175",
    artist: "Torgaar",
    gameUnlock: true,
  },
  golden: {
    name: "Golden",
    copies: "N/A",
    color: "#d9b552",
    artist: "Torgaar",
    gameUnlock: true,
    versions: [
      { name: "Golden Clock (Original)", img: "goldenclock.png" },
      { name: "Golden (New)", img: "golden.png" },
    ],
  },
  rainbowcoolguy: {
    name: "Cool Guy (Rainbow Glasses)",
    copies: "1/3",
    color: "#01a0e6",
    artist: "Chairlord & Torgaar",
  },
  coolerguy: {
    name: "Cool Guy (Cooler)",
    copies: "1/2",
    color: "#93c3f7",
    artist: "Chairlord & Torgaar",
  },
  coolerguytexture: {
    name: "Cool Guy (Cooler Texture)",
    copies: "1/2",
    color: "#1f2b80",
    artist: "Chairlord & Torgaar",
  },
  thecat: {
    name: "The Cat",
    copies: "1/1",
    color: "#df191f",
    desc: "First Place",
    gold: true,
    artist: "Mcdongos",
    firstPlace: true,
  },
  efanballoon: {
    name: "Efan Balloon",
    copies: "1/1",
    color: "#1801aa",
    desc: "Honorary",
    gold: true,
    artist: "Torgaar",
    honorary: true,
  },
  deacy: {
    name: "Deacy",
    copies: "1/1",
    color: "#0cb964",
    desc: "Honorary",
    gold: true,
    artist: "Dbumgarner",
    honorary: true,
  },
  triplet: {
    name: "Tung Tung Tung Sahur",
    copies: "1/2",
    color: "#e5ab52",
    artist: "jude",
  },
  cityboi: {
    name: "City Boy",
    copies: "1/11",
    color: "#165392",
    artist: "Torgaar & Ligmadaddy69",
    unlockCode: true,
  },
  cityboilegend: {
    name: "City Boy (Legendary)",
    copies: "1/2",
    color: "#135fbb",
    artist: "Torgaar & Ligmadaddy69",
  },
  coolguylogo: {
    name: "Cool Guy (Logo)",
    copies: "1/5",
    color: "#2493d4",
    artist: "Torgaar",
  },
  coolguylogomonogram: {
    name: "Cool Guy (Logo Monogram Special Edition)",
    copies: "1/3",
    color: "#348fc4",
    artist: "Torgaar",
  },
  coolguysignature: {
    name: "Cool Guy (Signature Logo)",
    copies: "1/3",
    color: "#7fb8e0",
    artist: "Torgaar",
    unlockCode: true,
  },
  coolguytorgaarsignature: {
    name: "Cool Guy (Torgaar Signature)",
    copies: "1/1",
    color: "#d4a51f",
    desc: "Honorary",
    gold: true,
    artist: "Torgaar",
    honorary: true,
    versions: [
      { name: "Original", img: "coolguytorgaarog.png" },
      { name: "Remaster", img: "coolguytorgaarsignature.png" },
    ],
  },
  coolguyoregon: {
    name: "Cool Guy (Oregon Signature)",
    copies: "1/3",
    color: "#076b65",
    artist: "Torgaar",
    unlockCode: true,
  },
  mistymountains: {
    name: "Misty Mountains",
    copies: "1/1",
    color: "#713e34",
    desc: "Honorary",
    gold: true,
    artist: "Novalis & Torgaar",
    honorary: true,
  },
  jimbotree: {
    name: "J_imbo Tree",
    copies: "1/1",
    color: "#3ab5fd",
    desc: "Honorary",
    gold: true,
    artist: "Seppe & Torgaar",
    honorary: true,
  },
  smiley: {
    name: "Smiley",
    copies: "1/1",
    color: "#6eb9f6",
    desc: "First Place",
    gold: true,
    artist: "Torgaar",
    firstPlace: true,
  },
  deathfire: {
    name: "Death Fire",
    copies: "1/1",
    color: "#3c71a0",
    desc: "First Place",
    gold: true,
    artist: "Jude",
    firstPlace: true,
  },
  earth: {
    name: "Earth",
    copies: "N/A",
    color: "#76a0bb",
    artist: "MidgeMidge22",
    gameUnlock: true,
  },
  tothemoon: {
    name: "Cool Guy (To the Moon)",
    copies: "1/7",
    color: "#232f71",
    artist: "Torgaar",
    unlockCode: true,
  },
  WINSTONTHEGREAT: {
    name: "WINSTONTHEGREAT",
    copies: "1/1",
    color: "#24babd",
    desc: "Honorary",
    gold: true,
    artist: "Torgaar & WINSTONISTHEBEST",
    honorary: true,
  },
  coolguygalaxy: {
    name: "Cool Guy (Galaxy)",
    copies: "1/3",
    color: "#243378",
    artist: "Torgaar",
    tag: "Shop S1",
  },
  coolguypristine: {
    name: "Cool Guy (Pristine)",
    copies: "1/3",
    color: "#bebcb9",
    artist: "Torgaar",
  },
  coolguymagma: {
    name: "Cool Guy (Magma)",
    copies: "1/3",
    color: "#680e0d",
    artist: "Torgaar",
  },
  coolguypurplemagma: {
    name: "Cool Guy (Purple Magma)",
    copies: "1/3",
    color: "#470d60",
    artist: "Torgaar",
  },
  earthpolluted: {
    name: "Earth (Polluted)",
    copies: "1/3",
    color: "#69858a",
    artist: "MidgeMidge22 & Torgaar",
    gameUnlock: true,
  },
  blockynosleep: {
    name: "Blocky (No Sleep)",
    copies: "1/3",
    color: "#0ebbd9",
    artist: "Crosby & Torgaar",
  },
  cubemouthdevourer: {
    name: "Cubemouth (Devourer)",
    copies: "N/A",
    color: "#3e54bb",
    artist: "Torgaar and Chairlord",
    blockySummer: true,
  },
  midgemidge: {
    name: "MidgeMidge",
    copies: "1/1",
    color: "#3317b1",
    desc: "Honorary",
    gold: true,
    artist: "Torgaar and MidgeMidge22",
    honorary: true,
  },
  blackbeard: {
    name: "Blocky (Blackbeard)",
    copies: "1/5",
    color: "#813a0a",
    artist: "Torgaar",
    unlockCode: true,
  },
  coolguypainted: {
    name: "Cool Guy (Painted)",
    copies: "1/5",
    color: "#c7ad23",
    artist: "Torgaar",
    unlockCode: true,
  },
  redtrail: {
    name: "Red Trail",
    copies: "1/3",
    color: "#c0392b",
    artist: "Torgaar & pedro",
    unlockCode: true,
  },
  coolguydeepbluespecial: {
    name: "Cool Guy (Deep Blue)",
    copies: "1/3",
    color: "#16086a",
    artist: "Torgaar",
    unlockCode: true,
  },
  demon: {
    name: "Demon",
    copies: "N/A",
    color: "#a20306",
    artist: "Torgaar",
    gameUnlock: true,
  },
  coolguymoney: {
    name: "Cool Guy (Money)",
    copies: "1/3",
    color: "#cbae62",
    artist: "Torgaar",
    tag: "Shop S2",
  },
  reddino: {
    name: "Dino (Red)",
    copies: "N/A",
    color: "#fc5455",
    artist: "Torgaar & Mcdongos",
    blockySummer: true,
  },
  bluedino: {
    name: "Dino (Blue)",
    copies: "N/A",
    color: "#025289",
    artist: "Torgaar & Mcdongos",
    blockySummer: true,
  },
  rainbowmonsterremastered: {
    name: "Rainbow Monster (Remastered)",
    copies: "N/A",
    color: "#f5b80d",
    artist: "Torgaar & Chairlord",
    blockySummer: true,
  },
  coolguy10: {
    name: "Cool Guy (1.10!)",
    copies: "1.10",
    color: "#30547a",
    artist: "Torgaar",
    tag: "Shop S1",
  },
  coolguytrail: {
    name: "Cool Guy (Trail)",
    copies: "1/4",
    color: "#009fe3",
    artist: "Torgaar",
  },
  coolguybloody: {
    name: "Cool Guy (Bloody)",
    copies: "1/5",
    color: "#a20306",
    artist: "Torgaar",
    blocktober: true,
  },
  alien: {
    name: "Alien",
    copies: "1/10",
    color: "#7ed957",
    artist: "Torgaar",
    blocktober: true,
  },
  alienblocktober: {
    name: "Alien (Yellow Eyes)",
    copies: "1/3",
    color: "#fadb43",
    artist: "Torgaar",
    blocktober: true,
  },
  burningheartremastered: {
    name: "Burning Heart (Remastered)",
    copies: "1/4",
    color: "#ffa629",
    artist: "Seppe",
    tag: "Seppe Collection",
  },
  clouds: {
    name: "Clouds",
    copies: "1/5",
    color: "#38b6ff",
    artist: "Seppe",
    tag: "Seppe Collection",
  },
  eyes: {
    name: "Eyes",
    copies: "1/5",
    color: "#9747ff",
    artist: "Seppe",
    tag: "Seppe Collection",
  },
  coolerguyredseppe: {
    name: "Cool Guy (Cooler Red)",
    copies: "1/3",
    color: "#930000",
    artist: "Seppe",
    tag: "Seppe Collection",
  },
  coolguyrainbowmonster: {
    name: "Cool Guy (Rainbow Monster)",
    copies: "1/5",
    color: "#f5b80d",
    artist: "Torgaar & Chairlord",
    tag: "Shop S2",
  },
  coolguysunset: {
    name: "Cool Guy (Sunset)",
    copies: "1/5",
    color: "#eaee00",
    artist: "Torgaar & Chairlord",
    tag: "Shop S2",
  },
  coolguydino: {
    name: "Cool Guy (Dino)",
    copies: "1/5",
    color: "#aefe61",
    artist: "Torgaar & Chairlord",
    tag: "Shop S2",
  },
  coolguyrounded: {
    name: "Cool Guy (Rounded)",
    copies: "1/5",
    color: "#009fe3",
    artist: "Torgaar",
    tag: "Rounded Series",
  },
  ghost: {
    name: "Ghost",
    copies: "1/5",
    color: "#FFFFFF",
    artist: "Torgaar",
    blocktober: true,
  },
  americancoolguy: {
    name: "Cool Guy (Very American)",
    copies: "1/10",
    color: "#FFFFFF",
    artist: "Mcdongos",
  },
  face: {
    name: "Ghost (Face)",
    copies: "1/5",
    color: "#FFFFFF",
    artist: "Torgaar",
    blocktober: true,
  },
};

window.ANIMATED_SKINS = [
  "smiley",
  "deathfire",
  "WINSTONTHEGREAT",
  "coolguymagma",
  "coolguypurplemagma",
];

window.SKIN_IMAGE_OVERRIDES = {
  coolguytrail: "coolguy.png",
};

window.SOLID_SKIN_COLORS = {
  default: "#335699",
  redtrail: "red",
};

window.skinFileExtension = function (id) {
  return window.ANIMATED_SKINS.includes(id) ? "gif" : "png";
};

window.skinImageFile = function (id) {
  if (id === "default") return "blockoverit.png";
  if (window.SKIN_IMAGE_OVERRIDES[id]) return window.SKIN_IMAGE_OVERRIDES[id];
  return id + "." + window.skinFileExtension(id);
};
