
window.SKIN_DEFINITIONS = {
  default: {
    name: "Blocky",
    copies: "N/A",
    color: "#335699",
    gameUnlock: true,
    artist: "Block Over It Dimension"
  },
  chairlord: {
    name: "Chairlord",
    copies: "1/1",
    color: "#d4d2c7",
    desc: "First Place",
    gold: true,
    artist: "Chairlord",
    firstPlace: true,
  },
  sunset: {
    name: "Sunset",
    copies: "1/2",
    color: "#eaee00",
    artist: "chairlord",
  },
  rainbowmonster: {
    name: "Rainbow Monster",
    collection: "Rainbow Monster",
    copies: "1/10",
    color: "#f51600",
    artist: "chairlord",
  },
  burningheart: {
    name: "Burning Heart",
    collection: "Burning Heart",
    copies: "1/3",
    color: "#130c10",
    artist: "Seppe",
  },
  tv: { name: "TV", copies: "1/2", color: "#f1eef4", artist: "Seppe" },
  cubemouth: {
    name: "Cube Mouth",
    collection: "Cube Mouth",
    copies: "1/6",
    color: "#1101d1",
    artist: "chairlord",
  },
  firstplacedaddy: {
    name: "First Place Daddy",
    copies: "1/1",
    color: "#eee6e6",
    desc: "First Place",
    gold: true,
    artist: "Ligmadaddy69 & Torgaar",
    firstPlace: true,
  },
  dino: {
    name: "Dino",
    collection: "Dino",
    copies: "1/68",
    color: "#aefe61",
    artist: "Mcdongos",
  },
  emo: {
    name: "Emotions",
    collection: "Emotions",
    copies: "1/3",
    color: "#398dfa",
    artist: "ejohnson",
  },
  emo2: {
    name: "Emotions 2",
    collection: "Emotions",
    copies: "1/5",
    color: "#476ffa",
    artist: "ejohnson",
  },
  emo3: {
    name: "Emotions 3",
    collection: "Emotions",
    copies: "1/5",
    color: "#388bf6",
    artist: "ejohnson",
  },
  kingbanana: {
    name: "King Banana",
    copies: "1/13",
    color: "#f2c94c",
    artist: "Torgaar",
    unlockCode: true,
  },
  j_imbo: {
    name: "J_imbo",
    copies: "1/1",
    color: "#0a9cdd",
    desc: "First Place",
    gold: true,
    artist: "Torgaar",
    firstPlace: true,
  },
  bluecoins: {
    name: "Blue Coins",
    copies: "N/A",
    color: "#2976bd",
    artist: "Torgaar",
    gameUnlock: true,
    versions: [
      {
        name: "Blue Gem", img: "bluegem.png",
        name: "Blue Coins", img: "bluecoins.png"}
    ]
  },
  coolguy: {
    name: "Cool Guy",
    collection: "Cool Guy",
    copies: "1/5",
    color: "#009fe3",
    artist: "Torgaar",
    competitive: true,
  },
  goldcoolguy: {
    name: "Golden Cool Guy",
    collection: "Cool Guy",
    copies: "1/1",
    color: "#dcb86f",
    artist: "Torgaar",
    competitive: true,
  },
  rainbownoir: {
    name: "Rainbow Monster (Noir)",
    collection: "Rainbow Monster",
    copies: "1/3",
    color: "#7e8185",
    artist: "Chairlord & Torgaar",
  },
  rainbowretro: {
    name: "Rainbow Monster (Retro)",
    collection: "Rainbow Monster",
    copies: "1/3",
    color: "#e9a13e",
    artist: "Chairlord & Torgaar",
  },
  vintageemo: {
    name: "Emotions (Vintage)",
    collection: "Emotions",
    copies: "1/3",
    color: "#85bdd4",
    artist: "ejohnson & Torgaar",
  },
  coolguyglassesdown: {
    name: "Cool Guy (Glasses Down)",
    collection: "Cool Guy",
    copies: "1/1",
    color: "#019adc",
    artist: "Torgaar",
    competitive: true,
  },
  dasher: {
    name: "Dasher",
    collection: "Dasher",
    copies: "1/1",
    color: "#e8e800",
    desc: "Honorary",
    gold: true,
    artist: "Chairlord",
    honorary: true,
  },
  dasher2: {
    name: "Dasher 2",
    collection: "Dasher",
    copies: "1/1",
    color: "#00e813",
    desc: "Honorary",
    gold: true,
    artist: "Chairlord",
    honorary: true,
  },
  metallic: {
    name: "Metallic Fire",
    copies: "N/A",
    color: "#df433d",
    artist: "Torgaar",
    gameUnlock: true,
    versions: [
      { name: "Original", img: "metallic_old.png" },
      { name: "Old", img: "metallic.png" },
      { name: "New", img: "metallicnew.png" },
    ],
  },
  legendsgalaxy: {
    name: "Galaxy (Legends Edition)",
    collection: "Galaxy",
    copies: "1/3",
    color: "#71b5d5",
    artist: "Torgaar",
    competitive: true,
  },
  galaxy: {
    name: "Galaxy",
    collection: "Galaxy",
    copies: "N/A",
    color: "#243175",
    artist: "Torgaar",
    gameUnlock: true,
  },
  golden: {
    name: "Golden",
    copies: "N/A",
    color: "#d9b552",
    artist: "Torgaar",
    gameUnlock: true,
    versions: [
      { name: "Golden Clock (Original)", img: "goldenclock.png" },
      { name: "Golden (Old))", img: "golden.png" },
      { name: "Golden (New)", img: "goldennew.png" },
    ],
  },
  rainbowcoolguy: {
    name: "Cool Guy (Rainbow Glasses)",
    collection: "Cool Guy",
    copies: "1/3",
    color: "#01a0e6",
    artist: "Chairlord & Torgaar",
  },
  coolerguy: {
    name: "Cool Guy (Cooler)",
    collection: "Cool Guy",
    copies: "1/2",
    color: "#93c3f7",
    artist: "Chairlord & Torgaar",
  },
  coolerguytexture: {
    name: "Cool Guy (Cooler Texture)",
    collection: "Cool Guy",
    copies: "1/2",
    color: "#1f2b80",
    artist: "Chairlord & Torgaar",
  },
  thecat: {
    name: "The Cat",
    copies: "1/1",
    color: "#df191f",
    desc: "First Place",
    gold: true,
    artist: "Mcdongos",
    firstPlace: true,
  },
  efanballoon: {
    name: "Efan Balloon",
    copies: "1/1",
    color: "#1801aa",
    desc: "Honorary",
    gold: true,
    artist: "Torgaar",
    honorary: true,
  },
  deacy: {
    name: "Deacy",
    copies: "1/1",
    color: "#0cb964",
    desc: "Honorary",
    gold: true,
    artist: "Dbumgarner",
    honorary: true,
  },
  triplet: {
    name: "Tung Tung Tung Sahur",
    copies: "1/2",
    color: "#e5ab52",
    artist: "jude",
  },
  cityboi: {
    name: "City Boy",
    collection: "City Boy",
    copies: "1/11",
    color: "#165392",
    artist: "Torgaar & Ligmadaddy69",
    unlockCode: true,
  },
  cityboilegend: {
    name: "City Boy (Legendary)",
    collection: "City Boy",
    copies: "1/2",
    color: "#135fbb",
    artist: "Torgaar & Ligmadaddy69",
  },
  coolguylogo: {
    name: "Cool Guy (Logo)",
    collection: "Cool Guy",
    copies: "1/5",
    color: "#2493d4",
    artist: "Torgaar",
  },
  coolguylogomonogram: {
    name: "Cool Guy (Logo Monogram Special Edition)",
    collection: "Cool Guy",
    copies: "1/3",
    color: "#348fc4",
    artist: "Torgaar",
  },
  coolguysignature: {
    name: "Cool Guy (Signature Logo)",
    collection: "Cool Guy",
    copies: "1/3",
    color: "#7fb8e0",
    artist: "Torgaar",
    unlockCode: true,
    versions: [
      { name: "Original", img: "coolguysignature.png" },
      { name: "Remaster", img: "coolguylogosignature.png" },
    ],
  },
  coolguytorgaarsignature: {
    name: "Cool Guy (Torgaar Signature)",
    collection: "Cool Guy",
    copies: "1/1",
    color: "#d4a51f",
    desc: "Honorary",
    gold: true,
    artist: "Torgaar",
    honorary: true,
    versions: [
      { name: "Original", img: "coolguytorgaarog.png" },
      { name: "Remaster", img: "coolguytorgaarsignature.png" },
    ],
  },
  coolguyoregon: {
    name: "Cool Guy (Oregon Signature)",
    collection: "Cool Guy",
    copies: "1/3",
    color: "#076b65",
    artist: "Torgaar",
    unlockCode: true,
    versions: [
      { name: "Original", img: "coolguyoregon.png" },
      { name: "Remaster", img: "coolguyoregonnew.png" },
    ],
  },
  mistymountains: {
    name: "Misty Mountains",
    copies: "1/1",
    color: "#713e34",
    desc: "Honorary",
    gold: true,
    artist: "Novalis & Torgaar",
    honorary: true,
  },
  jimbotree: {
    name: "J_imbo Tree",
    copies: "1/1",
    color: "#3ab5fd",
    desc: "Honorary",
    gold: true,
    artist: "Seppe & Torgaar",
    honorary: true,
  },
  smiley: {
    name: "Smiley",
    copies: "1/1",
    color: "#6eb9f6",
    desc: "First Place",
    gold: true,
    artist: "Torgaar",
    firstPlace: true,
  },
  deathfire: {
    name: "Death Fire",
    copies: "1/1",
    color: "#3c71a0",
    desc: "First Place",
    gold: true,
    artist: "Jude",
    firstPlace: true,
  },
  earth: {
    name: "Earth",
    collection: "Earth",
    copies: "N/A",
    color: "#76a0bb",
    artist: "MidgeMidge22",
    gameUnlock: true,
  },
  tothemoon: {
    name: "Cool Guy (To the Moon)",
    collection: "Cool Guy",
    copies: "1/7",
    color: "#232f71",
    artist: "Torgaar",
    unlockCode: true,
  },
  WINSTONTHEGREAT: {
    name: "WINSTONTHEGREAT",
    copies: "1/1",
    color: "#24babd",
    desc: "Honorary",
    gold: true,
    artist: "Torgaar & WINSTONISTHEBEST",
    honorary: true,
  },
  coolguygalaxy: {
    name: "Cool Guy (Galaxy)",
    collection: "Cool Guy",
    copies: "1/3",
    color: "#243378",
    artist: "Torgaar",
    tag: "Shop S1",
  },
  coolguypristine: {
    name: "Cool Guy (Pristine)",
    collection: "Cool Guy",
    copies: "1/3",
    color: "#bebcb9",
    artist: "Torgaar",
  },
  earthpolluted: {
    name: "Earth (Polluted)",
    collection: "Earth",
    copies: "1/3",
    color: "#69858a",
    artist: "MidgeMidge22 & Torgaar",
    gameUnlock: true,
  },
  blockynosleep: {
    name: "Blocky (No Sleep)",
    collection: "Blocky",
    copies: "1/3",
    color: "#0ebbd9",
    artist: "Crosby & Torgaar",
  },
  cubemouthdevourer: {
    name: "Cubemouth (Devourer)",
    collection: "Cube Mouth",
    copies: "1/3",
    color: "#3e54bb",
    artist: "Torgaar & Chairlord",
    blockySummer: true,
  },
  midgemidge: {
    name: "MidgeMidge",
    copies: "1/1",
    color: "#3317b1",
    desc: "Honorary",
    gold: true,
    artist: "Torgaar & MidgeMidge22",
    honorary: true,
  },
  blackbeard: {
    name: "Blackbeard",
    copies: "1/11",
    color: "#813a0a",
    artist: "Torgaar",
    unlockCode: true,
  },
  coolguypainted: {
    name: "Cool Guy (Painted)",
    collection: "Cool Guy",
    copies: "1/5",
    color: "#c7ad23",
    artist: "Torgaar",
    unlockCode: true,
  },
  redtrail: {
    name: "Red Trail",
    copies: "1/3",
    color: "#c0392b",
    artist: "Torgaar & pedro",
    unlockCode: true,
  },
  coolguydeepbluespecial: {
    name: "Cool Guy (Deep Blue)",
    collection: "Cool Guy",
    copies: "1/3",
    color: "#16086a",
    artist: "Torgaar",
    unlockCode: true,
  },
  demon: {
    name: "Nightmare",
    copies: "N/A",
    color: "#000000",
    artist: "Torgaar",
    gameUnlock: true,
    versions: [
      {
        name: "Demon", img: "demon.png",
      },
      {name: "Nightmare", img: "nightmare.png"}
    ]
  },
  coolguymoney: {
    name: "Cool Guy (Money)",
    collection: "Cool Guy",
    copies: "1/3",
    color: "#cbae62",
    artist: "Torgaar",
    tag: "Shop S1",
  },
  reddino: {
    name: "Dino (Red)",
    collection: "Dino",
    copies: "N/A",
    color: "#fc5455",
    artist: "Torgaar & Mcdongos",
    blockySummer: true,
  },
  bluedino: {
    name: "Dino (Blue)",
    collection: "Dino",
    copies: "N/A",
    color: "#025289",
    artist: "Torgaar & Mcdongos",
    blockySummer: true,
  },
  rainbowmonsterremastered: {
    name: "Rainbow Monster (Remastered)",
    collection: "Rainbow Monster",
    copies: "1/2",
    color: "#f5b80d",
    artist: "Torgaar & Chairlord",
    blockySummer: true,
  },
  coolguy10: {
    name: "Cool Guy (1.10!)",
    collection: "Cool Guy",
    copies: "1.10",
    color: "#30547a",
    artist: "Torgaar",
    tag: "Shop S1",
  },
  coolguytrail: {
    name: "Cool Guy (Trail)",
    collection: "Cool Guy",
    copies: "1/4",
    color: "#009fe3",
    artist: "Torgaar",
  },
  coolguybloody: {
    name: "Cool Guy (Bloody)",
    collection: "Cool Guy",
    copies: "1/5",
    color: "#a20306",
    artist: "Torgaar",
    blocktober: true,
  },
  alien: {
    name: "Alien",
    collection: "Alien",
    copies: "1/10",
    color: "#7ed957",
    artist: "Torgaar",
    blocktober: true,
  },
  alienblocktober: {
    name: "Alien (Martian)",
    collection: "Alien",
    copies: "1/5",
    color: "#fadb43",
    artist: "Torgaar",
    blocktober: true,
  },
  burningheartremastered: {
    name: "Burning Heart (Remastered)",
    collection: "Burning Heart",
    copies: "1/8",
    color: "#ffa629",
    artist: "Seppe",
    tag: "Seppe Collection",
  },
  clouds: {
    name: "Clouds",
    copies: "1/5",
    color: "#38b6ff",
    artist: "Seppe",
    tag: "Seppe Collection",
  },
  eyes: {
    name: "Eyes",
    copies: "1/5",
    color: "#9747ff",
    artist: "Seppe",
    tag: "Seppe Collection",
  },
  coolerguyredseppe: {
    name: "Cool Guy (Cooler Red)",
    collection: "Cool Guy",
    copies: "1/3",
    color: "#930000",
    artist: "Seppe",
    tag: "Seppe Collection",
  },
  coolguyrainbowmonster: {
    name: "Cool Guy (Rainbow Monster)",
    collection: "Cool Guy",
    copies: "1/5",
    color: "#f5b80d",
    artist: "Torgaar & Chairlord",
    tag: "Shop S2",
  },
  coolguysunset: {
    name: "Cool Guy (Sunset)",
    collection: "Cool Guy",
    copies: "1/5",
    color: "#eaee00",
    artist: "Torgaar & Chairlord",
    tag: "Shop S2",
  },
  coolguydino: {
    name: "Cool Guy (Dino)",
    collection: "Cool Guy",
    copies: "1/5",
    color: "#aefe61",
    artist: "Torgaar & Chairlord",
    tag: "Shop S2",
  },
  coolguyrounded: {
    name: "Cool Guy (Rounded)",
    collection: "Cool Guy",
    copies: "1/5",
    color: "#009fe3",
    artist: "Torgaar",
    tag: "Rounded Series",
  },
  ghost: {
    name: "Ghost",
    copies: "1/5",
    color: "#FFFFFF",
    artist: "Torgaar",
    blocktober: true,
  },
  americancoolguy: {
    name: "Cool Guy (Very American)",
    collection: "Cool Guy",
    copies: "1/10",
    color: "#FFFFFF",
    artist: "Mcdongos",
  },
  desert: {
    name: "Desert",
    copies: "1/2",
    color: "#ede98a",
    artist: "Seppe & Torgaar",
    tag: "Seppe Collection",
  },
  coolguyfunky: {
    name: "Cool Guy (Funky)",
    copies: "1/1",
    collection: "Cool Guy",
    color: "#ffa629",
    artist: "seppe",
    tag: "Seppe Collection"
  },
  coolguypumpkin: {
    name: "Cool Guy (Pumpkin)",
    copies: "1/3",
    collection: "Cool Guy",
    color: "#d7ac73",
    artist: "Mcdongos & Torgaar",
    blocktober: true
  },
  dinoclordconcept: {
    name: "Dino (Clord 'Dragon' Concept)",
    copies: "1/1",
    collection: "Dino",
    color: "#aefe61",
    artist: "Torgaar, Chairlord, & Mcdongos",
    tag: "Clord Concept S1"
  },
  pinnochio: {
    name: "Pinnochio",
    copies: "1/3",
    color: "#dba465",
    artist: "Torgaar",
    tag: "Clord Concept S1"
  },
  coolguysignatureconcept: {
    name: "Cool Guy (Signature Logo-Clord Concept)",
    copies: "1/4",
    collection: "Cool Guy",
    color: "#7fb8e0",
    artist: "Torgaar",
    tag: "Clord Concept S3"
  },
  chicken: {
    name: "Chicken",
    copies: "1/8",
    artist: "Deacon",
    tag: "Farm",
    color: "#ef8313"
  },
  pig: {
    name: "Pig",
    copies: "1/10",
    artist: "Deacon",
    tag: "Farm",
    color: "#ea75c9",
  },
  coolguyfarmer: {
    name: "Cool Guy (Farmer)",
    copies: "1/2",
    collection: "Cool Guy",
    artist: "Deacon",
    color: "#0d99ff",
    tag: "Farm"
  },
  cat: {
    name: "Cat",
    copies: "1/11",
    collection: "Cat",
    artist: "Deacon",
    color: "#fff1c0",
    tag: "Farm"
  },
  catblack: {
    name: "Cat (Black)",
    copies: "1/5",
    collection: "Cat",
    artist: "Deacon & Torgaar",
    color: "#000000",
    tag: "Farm"
  },
  catdark: {
    name: "Cat (In the Dark)",
    copies: "1/1",
    collection: "Cat",
    artist: "Deacon & Torgaar",
    color: "#1e1e1e",
    tag: "Farm"
  },
  cattabby: {
    name: "Cat (Tabby)",
    copies: "1/6",
    collection: "Cat",
    artist: "Deacon & Torgaar",
    color: "#ff751f",
    tag: "Farm"
  },
  coolguysad: {
    name: "Cool Guy (Sad)",
    copies: "1/6",
    collection: "Cool Guy",
    artist: "MidgeMidge22",
    color: "#009fe3",
    tag: "Shop S3"
  },
  coolguymagmanew: {
    name: "Cool Guy (Magma)",
    copies: "1/5",
    collection: "Cool Guy",
    artist: "Deacon",
    color: "#ff751f",
    tag: "Shop S3"
  },
  catlavender: {
    name: "Cat (Lavender)",
    copies: "1/3",
    collection: "Cat",
    artist: "Torgaar & Deacon",
    color: "#272030",
    tag: "Farm"
  },
  coolguyalien: {
    name: "Cool Guy (Alien)",
    copies: "1/4",
    collection: "Cool Guy",
    artist: "MidgeMidge22 & Torgaar",
    color: "#7ed957",
    blocktober: "true"
  },
  coolguyalienalternate: {
    name: "Cool Guy (Alien Alternate)",
    copies: "1/2",
    collection: "Cool Guy",
    artist: "MidgeMidge22 & Torgaar",
    color: "#ff751f",
    blocktober: true,
    tag: "Extra Styles Blocktober"
  },
  coolguyalientraditional: {
    name: "Cool Guy (Alien Traditional)",
    copies: "1/3",
    collection: "Cool Guy",
    artist: "Torgaar & MidgeMidge22",
    color: "#38b6ff",
    blocktober: true,
    tag: "Extra Styles Blocktober"
  },
  coolguygreenstripes: {
    name: "Cool Guy (Stripes Green)",
    copies: "N/A",
    collection: "Cool Guy",
    artist: "Torgaar",
    color: "#a8d67c",
  },
  coolguyorangestripes: {
    name: "Cool Guy (Stripes Orange)",
    copies: "N/A",
    collection: "Cool Guy",
    artist: "Torgaar",
    color: "#ff751f",
  },
  coolguybluestripes: {
    name: "Cool Guy (Stripes Blue)",
    copies: "N/A",
    collection: "Cool Guy",
    artist: "Torgaar",
    color: "#0879bf",
  },
  skeleton: {
    name: "Skeleton",
    copies: "1/3",
    collection: "Skeleton",
    artist: "Mcdongos",
    color: "#dee7ec",
    blocktober: true,
  },
  skeletonred: {
    name: "Skeleton (Red)",
    copies: "1/3",
    collection: "Skeleton",
    artist: "Mcdongos",
    color: "#ff3131",
    blocktober: true,
    tag: "Extra Styles Blocktober"
  },
  skeletonblue: {
    name: "Skeleton (Blue Glow)",
    copies: "1/3",
    collection: "Skeleton",
    artist: "Mcdongos",
    color: "#38b6ff",
    blocktober: true,
    tag: "Extra Styles Blocktober"
  },
  skeletoninverted: {
    name: "Skeleton (Inverted)",
    copies: "1/3",
    collection: "Skeleton",
    artist: "Mcdongos",
    color: "#000000",
    blocktober: true,
    tag: "Extra Styles Blocktober"
  },
};

window.ANIMATED_SKINS = [
  "smiley",
  "deathfire",
  "WINSTONTHEGREAT",
];

window.SKIN_IMAGE_OVERRIDES = {
  coolguytrail: "coolguy.png",
  dino: "dinoskin.png",
  bluedino: "bluedinoskin.png",
  reddino: "reddinoskin.png",
  coolguyreflection: "coolguyreflectionwhite.png",
  coolguysignature: "coolguylogosignature.png",
  metallic: "metallicnew.png",
  golden: "goldennew.png",
  ghost: "ghostnew.png",
  dinoclordconcept: "dinodragonchairlord.png",
  coolguyoregon: "coolguyoregonnew.png",
  demon: "nightmare.png",
  coolguysignatureconcept: "coolguysignaturechairlord.png",
  pinnochio: "pinnochiochairlord.png",
  alienblocktober: "alienmartian.png"
};

window.SOLID_SKIN_COLORS = {
  default: "#335699",
  redtrail: "red",
};

window.skinFileExtension = function (id) {
  return window.ANIMATED_SKINS.includes(id) ? "gif" : "png";
};

window.skinImageFile = function (id) {
  if (id === "default") return "blockoverit.png";
  if (window.SKIN_IMAGE_OVERRIDES[id]) return window.SKIN_IMAGE_OVERRIDES[id];
  return id + "." + window.skinFileExtension(id);
};
